version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: survivops
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./sql/init.sql:/data/application/init.sql